

// APP.H
#define APP_BOARD_LED_RED 29UL
#define APP_BOARD_LED_GREEN 30UL
#define APP_BOARD_LED_BLUE 31UL
#define APP_BOARD_SW2 19UL
#define APP_BOARD_SW3 26UL
#define APP_BOARD_TEST_LED APP_BOARD_LED_BLUE

